# 包含默认的 ESP32 manifest
include("$(PORT_DIR)/boards/manifest.py")

# 冻结我们的 frozen 目录中的Python文件
# 移除与默认manifest冲突的模块（如urequests, uasyncio等）
freeze("frozen", (
    "SCBoard.py",
    "ssd1306.py",
    "music.py",
    "tm1650.py",
    "SPL06.py",
    "servo.py",
    "dhtx.py",
    "mqtt.py",
    "mpu9250.py",
    "AHT20.py",
    "adxl345.py",
    "aremote.py",
    "asyn.py",
    "Blood.py",
    "blynklib.py",
    "blynklib_mp.py",
    "blynktimer.py",
    "bmp280.py",
    "DS3231.py",
    "font_to_bin.py",
    "interaction.py",
    "irremote.py",
    "lm35.py",
    "mars_rover_trail.py",
    "MAX7219.py",
    "mfrc522.py",
    "miot.py",
    "mixly_tool.py",
    "mixpy.py",
    "MSA301.py",
    "music_backup.py",
    "ds18x20x.py",
    "oled.py",
    "ori.py",
    "pca9685.py",
    "SCBoard_app.py",
    "SCBoard_game.py",
    "SCBoard_text.py",
    "SCBoard_weather_text.py",
    "sht20.py",
    "simple.py",
    "sonar.py",
    "zkspres.py",
    "zkspsimplev20.py",
    "send_fucking_data.py",
), opt=0)